ProyectoFinal/App1/urls.py
from django.urls import path 
from App1 import views 
from django.contrib.auth.views import LogoutView


urlpatterns = [
     path('', views.inicio, name="Inicio"),
     #path('Contactos', views.contactos, name="Contactos"),
     #path('Sugerencias', views.sugerencias, name="Sugernecias"),
     #path('Calificacion', views.calificacion, name="Calificacion"),
     path('getCalificacion', views.getCalificaciones, name="getCalificacion"),
     path('login',views.login_request, name="Login"),
     path('register', views.register, name='Register'),
     path('logout', LogoutView.as_view(template_name='App1/inicio.html'), name='Logout'),
     path('editarPerfil', views.editarPerfil, name="EditarPerfil"),
     path('cambiarContraseña', views.cambiarContrasena, name="cambiarContraseña"),
     path('verPerfil', views.verPerfil, name="VerPerfil"),
    # path('Acerca', views.acerca, name="Acerca"),
    # path('agregarAvatar', views.agregarAvatar, name="AgregarAvatar"),
    path('Calificacion',views.CalificacionList.as_view(),name='List'),
    path(r'^(?P<pk>\d+)$', views.CalificacionDetalle.as_view(),name='Detail'),
    path(r'^nuevo$', views.CalificacionCreacion.as_view(),name='New'),
    path(r'^editar/(?P<pk>\d+)$',views.CalificacionUpdate.as_view(),name='Edit'),
    path(r'^borrar/(?P<pk>\d+)$',views.CalificacionDelete.as_view(),name='Delete'),
    #
    path('Acerca',views.DescripcionList.as_view(),name='DescList'),
    path(r'^(?P<pk>\d+)$', views.DescripcionDetalle.as_view(),name='DescDetail'),
    path(r'^Descnuevo$', views.DescripcionCreacion.as_view(),name='DescNew'),
    path(r'^Desceditar/(?P<pk>\d+)$',views.DescripcionUpdate.as_view(),name='DescEdit'),
    path(r'^Descborrar/(?P<pk>\d+)$',views.DescripcionDelete.as_view(),name='DescDelete'),
    #
    path('ContactosList',views.ContactoList.as_view(),name='ContList'),
    path(r'^(?P<pk>\d+)$', views.ContactoDetalle.as_view(),name='ContDetail'),
    path(r'^Contnuevo$', views.ContactoCreacion.as_view(),name='ContNew'),
    path(r'^Conteditar/(?P<pk>\d+)$',views.ContactoUpdate.as_view(),name='ContEdit'),
    path(r'^Contborrar/(?P<pk>\d+)$',views.ContactoDelete.as_view(),name='ContDelete'),
    path('exito', views.exito, name="Exito"),
    path('exitopass', views.exitopass, name="Exitopass"),




]     

ProyectoFinal/ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App1.urls'))
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ProyectoFinal/App1/models.py
from django.db import models
from django.contrib.auth.models import User

class Avatar(models.Model):
     user = models.ForeignKey(User, on_delete=models.CASCADE)
    
     imagen = models.ImageField(upload_to='avatares', null=True, blank = True)
     def __str__(self):
         return f"{self.user} - {self.imagen}"
     
class Calificacion(models.Model):
    usuario= models.CharField(max_length=30)
    fecha= models.DateField()
    puntaje= models.CharField(max_length=1)
    comentario= models.CharField(max_length=140)
    def __str__(self):
        return f"Usuario: {self.usuario} - Fecha {self.fecha} - Puntaje{self.puntaje} - Comentario {self.comentario}"
   
class Descripcion(models.Model):
    acerca= models.CharField(max_length=140)
    def __str__(self):
        return f"Acerca: {self.acerca} "
      
class Contacto(models.Model):
    nombre= models.CharField(max_length=30)
    email= models.EmailField()
    telefono= models.CharField(max_length=15)
    consulta= models.CharField(max_length=140)
    def __str__(self):
        return f"Nombre: {self.nombre} - Email {self.email} - Telefono{self.telefono} - Consulta {self.consulta}"
         

ProyectoFinal/App1/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm ,UserChangeForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        # Saca los mensajes de ayuda
        help_texts = {k:"" for k in fields}

class AvatarFormulario(forms.Form):
    #Especificar los campos
    imagen = forms.ImageField(required=True) 

class UserEditForm(UserCreationForm):
    # Obligatorios
    email = forms.EmailField(label="Ingrese su email:")
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repetir la contraseña', widget=forms.PasswordInput)
   
    first_name = forms.CharField()
    last_name = forms.CharField()
    class Meta:
        model = User
        
        fields = ['email', 'password1', 'password2', 'first_name', 'last_name']       

class UserEditForm2(UserCreationForm):
    
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repetir la contraseña', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = []

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden.")
        return cleaned_data
       
      

class UserEditForm3(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #self.fields['username'].disabled = True
        self.fields.pop('password')
    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
        return user
    

class CalificacionFormulario(forms.Form):
    id= forms.IntegerField()
    usuario= forms.CharField(max_length=30)
    fecha=forms.DateField()
    puntaje= forms.CharField(max_length=1)
    comentario= forms.CharField(max_length=140)

class DescripcionFormulario(forms.Form):
    id= forms.IntegerField()
    acerca= forms.CharField(max_length=140)
    
class ContactoFormulario(forms.Form):
    id= forms.IntegerField()
    nombre= forms.CharField(max_length=30)
    email= forms.EmailField(label="Ingrese su email:")
    telefono= forms.CharField(max_length=15)
    consulta= forms.CharField(max_length=140)   

ProyectoFinal/App1/views.py
from typing import Any, Dict
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm 
from django.contrib.auth import login,logout,authenticate
from App1.forms import UserRegisterForm, UserEditForm , UserEditForm2 ,UserEditForm3 , AvatarFormulario
from django.contrib.auth.decorators import login_required
from App1.models import Avatar,Calificacion,Descripcion,Contacto
from django.contrib.auth.models import User
from datetime import date
from django.conf import settings
from django.core.mail import send_mail


def inicio(request):
    return render(request,'App1/inicio.html')

"""def contactos(request):
    return render(request,'App1/contacto.html',)"""

def sugerencias(request):
    return render(request,'App1/sugerencias.html')

def calificacion(request):
    return render(request,'App1/calificacion.html') 

def getCalificaciones(request):
    calificacion = request.GET.get('calificacion')
    puntos = calificacion.objects.filter(calificacion__icontains=calificacion)
    return render(request, 'App1/getcalificacion.html', {'puntos': puntos}) 
    
def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():  # Si pasó la validación de Django
            usuario = form.cleaned_data.get('username')
            contrasenia = form.cleaned_data.get('password')
            user = authenticate(username= usuario, password=contrasenia)
            if user is not None:
                login(request, user)
                return render(request, "App1/inicio.html", {"mensaje":f"Bienvenido {usuario}"}) and redirect('/')
            else:
                return render(request, "App1/login.html", {"mensaje":"Datos incorrectos"}) 
        else:
            return render(request, "App1/login.html", {"mensaje":"Formulario erroneo"}) 
    form = AuthenticationForm()
    return render(request, "App1/login.html", {"form": form})

def register(request):
      if request.method == 'POST':
            #form = UserCreationForm(request.POST)
            form = UserRegisterForm(request.POST)
            if form.is_valid():
                  username = form.cleaned_data['username']
                  email = form.cleaned_data['email']

                  if User.objects.filter(username=username).exists():
                        return render(request, "App1/registro.html", {"mensaje": "ERROR", "form": form, "error_msg": "El nombre de usuario ya está en uso"})

            
                  if User.objects.filter(email=email).exists():
                        return render(request, "App1/registro.html", {"mensaje": "ERROR", "form": form, "error_msg": "El correo electrónico ya está en uso"})

                  form.save()
                  return render(request,"App1/inicio.html" ,  {"mensaje":"Usuario Creado :)"}) and redirect('/')
      else:
            #form = UserCreationForm()       
            form = UserRegisterForm()     
      return render(request,"App1/registro.html" ,  {"mensaje":"ERROR","form":form})

@login_required
def editarPerfil(request):
    usuario = request.user

    if request.method == 'POST':

        miFormulario = UserEditForm3(request.POST)

        if miFormulario.is_valid():

            informacion = miFormulario.cleaned_data

            #usuario.username = informacion['username']
            usuario.first_name = informacion['first_name']
            usuario.last_name = informacion['last_name']
           

            usuario.save()

            usuario = request.user 
            email=request.user.email
            fname=request.user.first_name
            lname=request.user.last_name
            miFormulario = UserEditForm()
            return render(request, "App1/miPerfil.html", {"miFormulario": miFormulario, "usuario": usuario,"email": email, "first_name":fname, "last_name":lname, }) and redirect('/verPerfil#card')


    else:

        miFormulario = UserEditForm3()

    return render(request, "App1/editarPerfil.html", {"miFormulario": miFormulario, "usuario": usuario})
   
    

@login_required
def cambiarContrasena(request):
    usuario = request.user
    if request.method == 'POST':
        miFormulario = UserEditForm2(request.POST)
        if miFormulario.is_valid():
            password = miFormulario.cleaned_data['password1']
            usuario.set_password(password)
            usuario.save()
            return render(request, "App1/miPerfil.html", {"usuario": usuario}) and redirect('/exitopass')
    else:
        miFormulario = UserEditForm2()

    return render(request, "App1/cambiarContrasena.html", {"miFormulario": miFormulario, "usuario": usuario})   








def some_view(request):
    user_avatar = Avatar.objects.get(user=request.user)
    return render(request, 'inicio.html', {'user_avatar': user_avatar})

@login_required
def verPerfil(request):
    usuario = request.user 
    email=request.user.email
    fname=request.user.first_name
    lname=request.user.last_name
    miFormulario = UserEditForm()
     
    u = User.objects.get(username=request.user)
    try:
            avatar = Avatar.objects.get(user=u)
    except Avatar.DoesNotExist:
        avatar = None

    if request.method == 'POST':
            miFormulario = AvatarFormulario(request.POST, request.FILES) #aquí mellega toda la información del html
            if miFormulario.is_valid():   #Si pasó la validación de Django
                  if avatar is None:
                       avatar = Avatar(user=u, imagen=miFormulario.cleaned_data['imagen']) 
                  else:      
                       avatar.imagen = miFormulario.cleaned_data['imagen']
                  avatar.save()



                  usuario = request.user 
                  email=request.user.email
                  fname=request.user.first_name
                  lname=request.user.last_name
                  miFormulario = UserEditForm()
                  return render(request, "App1/miPerfil.html", {"miFormulario": miFormulario, "usuario": usuario,"email": email, "first_name":fname, "last_name":lname, }) and redirect('/verPerfil#card')

    else: 
            miFormulario= AvatarFormulario() #Formulario vacio para construir el html

    return render(request, "App1/miPerfil.html", {"miFormulario": miFormulario, "usuario": usuario,"email": email, "first_name":fname, "last_name":lname})





def acerca(request):
    return render(request,'App1/acercaDeMi.html')

from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import ListView
class CalificacionList(ListView):
    model =Calificacion
    template_name='calificacion_list.html'

   
    

from django.views.generic.detail import DetailView
class CalificacionDetalle(DetailView):
    model=Calificacion
    template_name= "calificacion_list.html"

from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

class CalificacionCreacion(LoginRequiredMixin,CreateView):
    model=Calificacion
    success_url="/Calificacion"
    fields= ['usuario','fecha','puntaje','comentario' ]

    def form_valid(self, form):
         form.instance.usuario=self.request.user
         return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
         context = super().get_context_data(**kwargs)
         context['fecha']=date.today().strftime('%d/%m/%Y')
         return context

   
from django.views.generic.edit import UpdateView
class CalificacionUpdate(UpdateView):
    model=Calificacion
    success_url= "/Calificacion"
    fields=['usuario','fecha','puntaje','comentario' ]

from django.views.generic.edit import DeleteView
class CalificacionDelete(LoginRequiredMixin,DeleteView):
    model=Calificacion
    success_url="/Calificacion"   

    """def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if not self.request.user.is_superuser:
            form.fields['usuario','fecha','puntaje','comentario'].widget.attrs['readonly'] = True
        return form """
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return redirect('Inicio')  # Reemplaza 'inicio' con el nombre de tu URL para la página de inicio

        return super().dispatch(request, *args, **kwargs)



"-------------------------------------------------------------------------------------------------"

class DescripcionList(ListView):
    model =Descripcion
    template_name='descripcion_list.html'

class DescripcionDetalle(DetailView):
    model=Descripcion
    template_name= "descripcion_list.html"

class DescripcionCreacion(LoginRequiredMixin,CreateView):
    model=Descripcion
    success_url="/Acerca"
    fields= ['acerca' ]
    """def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if not self.request.user.is_superuser:
            form.fields['acerca'].widget.attrs['readonly'] = True
        return form """
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return redirect('Inicio')  # Reemplaza 'inicio' con el nombre de tu URL para la página de inicio

        return super().dispatch(request, *args, **kwargs)


class DescripcionUpdate(UpdateView):
    model=Descripcion
    success_url= "/Acerca"
    fields= ['acerca' ]
    """def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if not self.request.user.is_superuser:
            form.fields['acerca'].widget.attrs['readonly'] = True
        return form """
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return redirect('Inicio')  # Reemplaza 'inicio' con el nombre de tu URL para la página de inicio

        return super().dispatch(request, *args, **kwargs)

class DescripcionDelete(LoginRequiredMixin,DeleteView):
    model=Descripcion
    success_url="/Acerca"   

ProyectoFinal/App1/templates/App1/Login.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head>
     <script src="../assets/js/color-modes.js"></script>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.111.3">
    <title>Signin Template · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/sign-in/">

    

    

<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    

    
    <!-- Custom styles for this template -->
    <link href="{% static 'App1/css/styles.css' %}" rel="stylesheet" />

  </head>
  <style>
    body {
      background-color: #1d1d1d; /* Color de fondo oscuro */
      color: #fff; /* Color de texto blanco */
    }
  </style>
  <body class="text-center" >
    

    


    <div class="container-fluid">
      <div class="row justify-content-center">
        
        <main class="form-signin col-12 col-md-6 col-lg-4">
          <form action="" method="POST" >
            {% csrf_token %}
            <img class="mb-4" src="{% static 'logo.png' %}" alt="" width="80" height="80">
            <h1 class="h3 mb-3 fw-normal">Ingrese su usuario</h1>

            {% if mensaje %}
              <p>{{ mensaje }}</p>
            {% endif %}

            <div class="form-floating">
              <input type="user" class="form-control" id="floatingInput" placeholder="username" name="username">
              <label for="floatingInput" style="color:#1d1d1d;">Username </label>
              
            </div>
            
            <br>
            <div class="form-floating">
              <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
              <label for="floatingPassword" style="color:#1d1d1d;">Password</label>
            </div>

            <br>
            <br>
            <button class="w-50 btn btn-lg btn-primary" type="submit">Sign in</button>
            <br>
            <br>
            <a class="btn btn-secondary btn-s text-uppercase" href="/">Atras</a>
            <p class="mt-5 mb-3 text-body-secondary">&copy; Koyshot</p>
           
          </form>
        </main>

      </div>
    </div>
  </body>
</html>

ProyectoFinal/App1/templates/App1/agregarAvatar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    <title>Cargar Avatar</title>
</head>
<body>
    <h3>Cargar Avatar</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ miFormulario.as_p}}
        <input type="submit" value="Actualizar">
    </form>
</body>
</html>

ProyectoFinal/App1/templates/App1/calificacion_confirm_delete.html
{% extends "App1/calificacion_list.html" %}

{% load static %}

{% block form %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
    $(document).ready(function() {
        $('#exampleModal').modal('show');
    });
</script>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel" style="color:#1d1d1d;">BORRAR</h1>
          
        </div>
        <div class="modal-body"> 
            <form method="post">  
            <form method="post">{% csrf_token %}
                ¿Estas seguro de que deseas borrar el comentario "{{ object }}"?
                <input type="submit" value="BORRAR">
                
            </form>    
            <script>
                function goBack() {
                    window.history.back();
                }
            </script>
            <a class="btn btn-primary btn-s text-uppercase" href="#" onclick="goBack()">Atras</a>
            
            </div>
        </div>
      </div>
    </div>

        
    
{% endblock %}

    
    
    

ProyectoFinal/App1/templates/App1/calificacion_form.html
{% extends "App1/calificacion_list.html" %}

{% load static %}

{% block form %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
    $(document).ready(function() {
        $('#exampleModal').modal('show');
    });
</script>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel" style="color:#1d1d1d;">Calificar</h1>
          
        </div>
        <div class="modal-body">   
                    <form method="post">
                        <style>     

                            form{ width:250px; margin:0 auto; padding:10px; border: 1px solid #d9d9d9;}
                            form p, form input[type = "submit"]{text-align:center; font-size:20px;}


                            input[type = "radio"]{ display:none;/*position: absolute;top: -1000em;*/}
                            label{ color:grey;}

                            .clasificacion{
                                direction: rtl;
                                unicode-bidi: bidi-override;
                            }

                            label:hover,
                            label:hover ~ label{color:orange;}
                            input[type = "radio"]:checked ~ label{color:orange;}

                    </style>
                <form method="post" action="{% url 'New' %}">
                    {% csrf_token %} 
                    User: <strong>{{request.user.username}}</strong>
                    <br>
                    Fecha {{fecha}}
                    <br>
                    Comentario {{ form.comentario }}
                <p class="clasificacion">
                <input id="radio1" type="radio" name="puntaje" value="5"><!--
                --><label for="radio1">★</label><!--
                --><input id="radio2" type="radio" name="puntaje" value="4"><!--
                --><label for="radio2">★</label><!--
                --><input id="radio3" type="radio" name="puntaje" value="3"><!--
                --><label for="radio3">★</label><!--
                --><input id="radio4" type="radio" name="puntaje" value="2"><!--
                --><label for="radio4">★</label><!--
                --><input id="radio5" type="radio" name="puntaje" value="1"><!--
                --><label for="radio5">★</label>
                
                </p>
                <input type="hidden" name="usuario" value="{{request.user.username}}">
                <input type="hidden" name="fecha" value="{{fecha}}">
                <input type="submit" value="Enviar" href="Calificacion#cali" >
                </form>
                <a class="btn btn-primary btn-s text-uppercase" href="Calificacion#cali">Atras</a>
            </div>
        </div>
      </div>
    </div>

        
    
{% endblock %}

ProyectoFinal/App1/templates/App1/calificacion_list.html
{% extends "App1/inicio.html" %}

{% load static %}

{% block clasi %}

<section class="page-section" id="contact">
<div id="cali" style="text-align: center;" >
<h1 style="color:#ffffff;">Calificaciones</h1>
</div>
<a class="btn btn-primary btn-s text-uppercase" href="{% url 'New' %}">Calificar</a>
    
<style>
  #scroll{
      border:1px solid;
      height:100px;
      width:300px;
      overflow-y:scroll;
      overflow-x:hidden;
      word-wrap: break-word;
  }
  </style>

   
   
{% for calificacion in object_list %}
        
          
          <div style="text-align: center; max-width: 300px; margin: 0 auto;">
            <div class="list-group">
              
              <a  class="list-group-item list-group-item-action active" aria-current="true">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">{{ calificacion.usuario }}</h5>
                  <small>{{ calificacion.fecha }}</small>
                  
                </div>
                <div id="scroll">
                   <p class="mb-1">{{ calificacion.comentario }}</p>
                </div>
                <small>Puntaje{{ calificacion.puntaje }}/5★</small>
                
               <!--  <a class="list-group-item list-group-item-action active"  href="{% url 'Edit' calificacion.id %}">Editar</a>
                -->
                {% if request.user.is_superuser %}
                <a class="list-group-item list-group-item-action active"  href="{% url 'Delete' calificacion.id %}">Borrar</a>
                {% endif %}

                
              </a>
              <br>
                <br>
                
            </div>                 
          </div> 
        </h4>     
      </div>  
         
                
        
        {% endfor %}
      </section> 

{% endblock %}

ProyectoFinal/App1/templates/App1/cambiarContrasena.html
{% extends "App1/inicio.html" %}

{% load static %}

{% block editarpass %}

    <!--Aquí va lo que cambia, y lo asociado a está vista :) -->
    <h1> Cambiar Contraseña</h1>
    <h1>De {{usuario}}</h1>
    

    <form action="" method="POST">
        {% csrf_token %}

        <!-- Acá está la magia de Django-->
        
        <table>

            {{ miFormulario.as_table }}
            

        </table>

        <input type="submit", value="Enviar">

    </form>  
    <a class="btn btn-primary btn-s text-uppercase" href="verPerfil#card">Atras</a>
    
{% endblock %}

ProyectoFinal/App1/templates/App1/getcalificacion.html
{% extends "App1/inicio.html" %}

{% load static %}




    

{% block calificacion %}


        
<label for="calificacion" class="form-label">RESULTADO DE BUSQUEDA</label>
  {% if puntos %}
    <ul>
    {% for punto in puntos %}
      <li>{{ punto.calificacion }} </li>
    {% endfor %}
    </ul>
  {% else %}
    <p>No se encontraro calificaciones con ese puntaje.</p>
  {% endif %}

{% endblock %}

ProyectoFinal/App1/templates/App1/miPerfil.html
{% extends "App1/inicio.html" %}

{% load static %}

{% block verrperfil %}

    <!--Aquí va lo que cambia, y lo asociado a está vista :) -->
    <style>
      body {
        background-color: #1d1d1d; /* Color de fondo oscuro */
        color: #fff; /* Color de texto blanco */
      }
    </style>
    <body class="text-center" >
    <div class="card " style="width: 22rem;" id="card">
        {% with avatares=request.user.avatar_set.all %}
        {% if avatares %}
        <div style="text-align: center;">
            <img height="180px" width="180px" style="border-radius: 50%;" src="{{avatares.0.imagen.url}}">
        </div>    
        {% else %}
          <div style="text-align: center;">
            <img src="{% static 'null.png' %}" alt="user" height="180px" width="180px" style="border-radius: 50%;">
          </div>        
        {% endif %}                        
        {% endwith %}
        <div style="text-align: center;">
            <a class="card-link" data-bs-toggle="modal" data-bs-target="#exampleModal" >Cambiar foto</a>
        </div>
        <div class="card-body">
            <div style="text-align: center;">  
                <h4 class="card-title">{{usuario}}</h4>
            </div>    
          <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>  -->
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Email:{{email}}</li>
          <li class="list-group-item">Nombre:{{first_name}}</li>
          <li class="list-group-item">Apellido:{{last_name}}</li>
        </ul>
        <div class="card-body">
          <a href="editarPerfil#id_first_name" class="card-link">Editar Perfil</a>
          <a href="cambiarContraseña#id_password1" class="card-link">Cambiar Contraseña</a>
        </div>
      </div>
    

  
      
      
      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" >
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel" style="color:#1d1d1d;">Cambiar Avatar</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <form method="POST" enctype="multipart/form-data" style="color:#1d1d1d;" >
                {% csrf_token %}
                {{ miFormulario.as_p}}            
            
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button  class="btn btn-primary" type="submit">Actualizar</button>
            </form>
            </div>
          </div>
        </div>
      </div>
    
     
    

    

{% endblock %}